### PR TITLE
Making BED.jl compatible with Automa v1

### PR DESCRIPTION
**Pull request by abhinavsns**
This maintains compatibility with XAM release v0.4.0

# A clear and descriptive title (No issue numbers please)

> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Types of changes

This PR implements the following changes:
_(Please tick any or all of the following that are applicable)_

* [ ] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :clipboard: Additional detail

- If you have implemented new features or behaviour
  - **Provide a description of the addition** in as many details as possible.

  - **Provide justification of the addition**.

  - **Provide a runnable example of use of your addition**. This lets reviewers
    and others try out the feature before it is merged or makes it's way to release.

- If you have changed current behaviour...
  - **Describe the behaviour prior to you changes**

  - **Describe the behaviour after your changes** and justify why you have made the changes,
    Please describe any breakages you anticipate as a result of these changes.

  - **Does your change alter APIs or existing exposed methods/types?**
    If so, this may cause dependency issues and breakages, so the maintainer
    will need to consider this when versioning the next release.

  - If you are implementing changes that are intended to increase performance, you
    should provide the results of a simple performance benchmark exercise
    demonstrating the improvement. Especially if the changes make code less legible.

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [x] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [ ] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [ ] :ok: All changes should be compatible with the latest stable version of Julia.
- [ ] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by kescobo** [comment]
Do we really need to conitnue testing on julia 1.0? That seems crazy.

But also, this is having a failure on v1.10, so something else is needed - is that actually related to this PR?

**Comment by abhinavsns** [comment]
Hello @kescobo, I think some confusion based on the title of the PR. I meant compat entry of the Automa dependency. I have changed it now.

**Comment by kescobo** [comment]
@abhinavsns Oh no - that was clear - I was just watching the early CI failures on julia v1.0 and thinking it was weird that we're still checking that .

I now see that at least some of the v!.0 julia tests pass, but *all* the release tests fail. It looks like the tests for those earlier julia versions are still pulling in Automa v0.8, whereas the current julia version correctly gets Automa v1.0.4. I'm guessing some indirect dependency is holding back Automa on the old julia version.

These all seem to be failing with 

```
Failed to precompile BED [8e4a8c10-cb6b-11e8-08d2-83478d609d67] to "/Users/runner/.julia/compiled/v1.10/BED/jl_8QBqBy".
ERROR: LoadError: UndefVarError: `Stream` not defined
```

**Comment by abhinavsns** [comment]
Ah I see, is there a way to reproduce the issue locally? I am unable to understand which exact julia version to use.

**Comment by abhinavsns** [comment]
okay I am able to reproduce the issue on julia v1.10.4 but have no idea how to fix.

seems like Automa now does not have `Streams` submodule https://github.com/BioJulia/BED.jl/blob/2e082b1a9f8c6c543e5544a90a7f970110ca7e6b/src/reader.jl#L5
but when it is changed to 
`import Automa: @mark, @markpos, @relpos, @abspos`

It fails at https://github.com/BioJulia/BED.jl/blob/2e082b1a9f8c6c543e5544a90a7f970110ca7e6b/src/reader.jl#L95
with `ERROR: LoadError: MethodError: no method matching setindex!(::Nothing, ::Vector{Symbol}, ::Symbol)`

**Comment by jakobnissen** [comment]
Superseded by #19.
Thanks for bringing this up.

**Pull request closed without merging**
